theme: jekyll-theme-minimal
title: Alberto Garcia Gonzalez
description: <b>Software developer</b> with 5+ years of experience in both academia and the business world, currently based out of Salt Lake City, Utah.<br><br> <b>agarciamog@gmail.com</b>
