theme: jekyll-theme-minimal
title: <img align="left" src="https://agarciamog.github.io/img/boss.png"> <br> Alberto Garcia
description: I am a <b>software developer</b> with 5+ years of experience in both academia and the business world, currently based out of Salt Lake City, Utah.<br><br> <b>agarciamog@gmail.com</b>
