theme: jekyll-theme-minimal
title: Alberto Garcia
description: Software developer with 5+ years of experience in both academia and the business world, currently based out of Salt Lake City, Utah.<br><br> <b>agarciamog@gmail.com</b>
